composter.lock
Roman-Khilevych/OSS pull request #1
Opened 2020-01-21 16:43 UTC by vlromaniuk

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-29 14:30 UTC, Roman-Khilevych requested changes

2020-01-29 14:30 UTC, Roman-Khilevych commented on app/design/frontend/parentLuma/default/registration.php
> +
Add comment

/**
 * Rokhi theme.
 *
 * @author Roman Khilevych <rokhi@smile.fr>
 * @copyright 2020 Rokhi
 */

2020-01-29 14:30 UTC, Roman-Khilevych commented on app/design/frontend/parentLuma/default/theme.xml
> +-->
Remove comment

2020-01-29 14:30 UTC, Roman-Khilevych commented on app/design/frontend/parentVlromaniuk/default/registration.php
> +
comment

2020-01-29 14:57 UTC, Roman-Khilevych requested changes

2020-01-29 14:57 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layouts.xml
> +-->
Комент

2020-01-29 14:57 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layout/override/theme/Magento/blank/default_head_blocks.xml
> +-->
Комент

2020-01-29 14:57 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layout/default_head_blocks.xml
> +        <script src="mage/polyfill.js"/>-->
Це тут лишнє

2020-01-29 14:57 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/override/base/catalog_product_view.xml
> +-->
Комент

2020-01-29 14:57 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/catalog_category_view.xml
> +-->
Комент

2020-01-29 15:00 UTC, Roman-Khilevych requested changes

2020-01-29 15:00 UTC, Roman-Khilevych commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/override/base/catalog_product_view.xml
> +        </referenceBlock>-->
Це тут лишнє

2020-01-30 19:24 UTC, vlromaniuk commented on app/design/frontend/parentLuma/default/registration.php
> +
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/parentLuma/default/theme.xml
> +-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/parentVlromaniuk/default/registration.php
> +
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layouts.xml
> +-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layout/override/theme/Magento/blank/default_head_blocks.xml
> +-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Theme/layout/default_head_blocks.xml
> +        <script src="mage/polyfill.js"/>-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/override/base/catalog_product_view.xml
> +-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/catalog_category_view.xml
> +-->
Fix

2020-01-30 19:25 UTC, vlromaniuk commented on app/design/frontend/vlromaniuk/default/Magento_Catalog/layout/override/base/catalog_product_view.xml
> +        </referenceBlock>-->
Fix

2020-01-31 09:42 UTC, Roman-Khilevych requested changes

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/catalog_product_view.xml
> +</page>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/cms_index_index.xml
> +
Дирка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/default_head_blocks.xml
> +</page>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/Common_layout_customization_task/default/Magento_Theme/layout/catalogsearch_advanced_index.xml
> +</page>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/Common_layout_customization_task/default/Magento_Theme/layout/default_head_blocks.xml
> +</page>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/list/toolbar.phtml
> + */
Комент правильний

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/down-gallery.phtml
> +<?= __('Down Gallery')?>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/down_filter.phtml
> +<?= __('Down Filter')?>
Пуста строка

2020-01-31 09:42 UTC, Roman-Khilevych commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/my_template.phtml
> +?>
Це нащо тут? Коменти додай в phtml файли.

2020-01-31 09:45 UTC, Roman-Khilevych requested changes

2020-01-31 09:45 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + */
Комент

2020-01-31 09:45 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> +    UP FILTER
Транслейт

2020-01-31 09:45 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + */
Комент

2020-01-31 09:45 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Theme/layout/catalog_category_view.xml
> +</page>
Пуста строка

2020-01-31 10:01 UTC, vlromaniuk commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/catalog_product_view.xml
> +</page>
Fix

2020-01-31 10:01 UTC, vlromaniuk commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/cms_index_index.xml
> +
Fix

2020-01-31 10:02 UTC, vlromaniuk commented on app/design/frontend/Common_layout_customization_task/default/Magento_Catalog/layout/default_head_blocks.xml
> +</page>
Fix

2020-01-31 10:02 UTC, vlromaniuk commented on app/design/frontend/Common_layout_customization_task/default/Magento_Theme/layout/catalogsearch_advanced_index.xml
> +</page>
Fix

2020-01-31 10:02 UTC, vlromaniuk commented on app/design/frontend/Common_layout_customization_task/default/Magento_Theme/layout/default_head_blocks.xml
> +</page>
Fix

2020-01-31 10:06 UTC, Roman-Khilevych commented
В phtml та php мають бути правильні коментарі. Не треба просто видаляти дефолтні.

2020-01-31 10:07 UTC, vlromaniuk commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/list/toolbar.phtml
> + */
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/down-gallery.phtml
> +<?= __('Down Gallery')?>
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/down_filter.phtml
> +<?= __('Down Filter')?>
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/hw/default/Magento_Catalog/templates/product/my_template.phtml
> +?>
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + */
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> +    UP FILTER
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + */
Fix

2020-01-31 10:08 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Theme/layout/catalog_category_view.xml
> +</page>
Fix

2020-01-31 10:11 UTC, Roman-Khilevych commented
В коментах першою строкою має бути описання даного файлу а не Vlromaniuk theme скрізь.

2020-01-31 10:12 UTC, vlromaniuk commented
> 
> 
> В коментах першою строкою має бути описання даного файлу а не Vlromaniuk theme скрізь.

Так як тоді правильно?

2020-01-31 10:19 UTC, Roman-Khilevych commented
Пишеш що в цьому файлі. Для прикладу - Для прикладу Vlromaniuk default catalog filter template.

2020-01-31 10:38 UTC, vlromaniuk commented
> 
> 
> Пишеш що в цьому файлі. Для прикладу - Vlromaniuk default catalog filter template.

Так годиться?

2020-01-31 10:44 UTC, Roman-Khilevych requested changes

2020-01-31 10:44 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Це дефолтний темплейт переписаний тобою а не Custom block under comment in product page

2020-01-31 10:44 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Це дефолтний темплейт переписаний тобою а не Custom block under filter
Тут має бути щось типу {Назва пекейджа} {назва теми} layer filter template

2020-01-31 10:50 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Fix

2020-01-31 10:50 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Fix

2020-01-31 10:59 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Це не кастом блок і навыть не блок.
Напиши {Назва пекейджа} {назва теми} layer filter template

2020-01-31 11:00 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Це не кастом блок і навыть не блок.
Напиши {Назва пекейджа} {назва теми} review form template

2020-01-31 11:03 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Виправив

2020-01-31 11:03 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Виправив

2020-01-31 11:07 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Ні не виправив.
Напиши {Назва пекейджа} {назва теми} review form template

2020-01-31 11:07 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Ні не виправив.
Напиши {Назва пекейджа} {назва теми} layer filter template

2020-01-31 11:10 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Magento Review. Template. review form tempate?

2020-01-31 11:21 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Template default review form template.
Template - це назва твого пекейджа

2020-01-31 11:23 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
а зрозумів

2020-01-31 11:32 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_Review/templates/form.phtml
> + *Custom block under comment in product page
Ти перепутав місцями коменти.

2020-01-31 11:33 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Ти перепутав місцями коменти.

2020-01-31 11:34 UTC, vlromaniuk commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
&$!#%

2020-01-31 11:37 UTC, Roman-Khilevych commented on app/design/frontend/template/default/Magento_LayeredNavigation/templates/layer/filter.phtml
> + *Custom block under filter
Добре)

2020-01-31 11:37 UTC, Roman-Khilevych approved these changes

2020-01-31 11:38 UTC, merged