class work
Roman-Khilevych/OSS pull request #17
Opened 2020-02-04 18:26 UTC by vlromaniuk

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-05 09:47 UTC, Roman-Khilevych requested changes

2020-02-05 09:47 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlcok/default/Magento_Cms/templates/editorialParent.phtml
> +*lessonsCmsBlcok default display text example
Назви файл так само як в коменті написав.

2020-02-05 09:47 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlcok/default/registration.php
> +Vlromaniuk theme.
LessonCmsBlcok default theme registration

2020-02-05 09:47 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlcok/default/Magento_Catalog/templates/product/widget/new/content/new_grid.phtml
> +*lessonsCmsBlcok default change grid template.
Шо таке Blcok, це якесь скорочення?)))

2020-02-05 09:48 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlcok/default/Magento_Catalog/templates/product/widget/new/content/new_grid.phtml
> +*lessonsCmsBlcok default change grid template.
Та перепутав символи), виправлю

2020-02-06 09:49 UTC, Roman-Khilevych commented
Передивись щераз коментарі свої, порівняй з тими що я писав тобі раніше і виправ всі.

2020-02-06 09:50 UTC, Roman-Khilevych commented
І передивлюйся свій код в МРі після того як запушив.

2020-02-06 09:53 UTC, vlromaniuk commented
> 
> 
> І передивлюйся свій код в МРі після того як запушив.

я дивлюсь і все ніби ок,

2020-02-06 09:54 UTC, Roman-Khilevych commented
> > І передивлюйся свій код в МРі після того як запушив.
> 
> я дивлюсь і все ніби ок,

Значить пару раз дивися, якщо з першого не бачиш.

2020-02-06 09:56 UTC, Roman-Khilevych requested changes

2020-02-06 09:56 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlcok/default/Magento_Catalog/templates/product/widget/new/content/new_grid.phtml
> +*lessonsCmsBlock default change grid template.
Нащо ти тут написав lessonsCmsBlock, тему не переіменував і в остальних файлах залишив blcok?

2020-02-06 15:09 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlcok/default/Magento_Catalog/templates/product/widget/new/content/new_grid.phtml
> +*lessonsCmsBlock default change grid template.
Fixed

2020-02-07 09:23 UTC, Roman-Khilevych requested changes

2020-02-07 09:23 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlock/default/Magento_Catalog/templates/product/widget/new/content/new_grid.phtml
> +*lessonsCmsBlock default change grid template.
lessonsCmsBlock default Catalog product widget new grid template.

2020-02-07 09:23 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
Неправильний комент.

2020-02-07 09:25 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
а как правильно?

2020-02-07 09:34 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
I don’t know English

2020-02-07 10:01 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
Передивися правильні коменти що я тобі писав, порівняй їх з імена файлів та шляхом тих файлів і зроби висновки як правильно писати коменти.

2020-02-07 10:13 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
lessonsCmsBlock default Cms dispaly a name template?

2020-02-07 10:26 UTC, Roman-Khilevych commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
lessonsCmsBlock default Cms display name example template?
В подальшому маєш без підказок вже сам писати.

2020-02-07 10:29 UTC, vlromaniuk commented on app/design/frontend/lessonsCmsBlock/default/Magento_Cms/templates/display_name_example.phtml
> +*lessonsCmsBlock default display text example
> 
> 
> lessonsCmsBlock default Cms display name example template?
> В подальшому маєш без підказок вже сам писати.

Посатраємся

2020-02-07 17:52 UTC, merged