css to less update
Roman-Khilevych/OSS pull request #27
Opened 2020-02-17 21:33 UTC by worzewolf

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-17 21:52 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Magento_Theme/web/css/source/_module_extend.less
> +  background-color: @custom__bg-color;
Custom слово не підходить. Можеш поміняти на назву теми.

2020-02-17 21:52 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Module_Review/web/css/source/_module.less
> +//  */
?

2020-02-17 21:52 UTC, Roman-Khilevych commented
Де описані всі кольори змінними?

2020-02-17 21:53 UTC, Roman-Khilevych commented
Де налаштована типографія?

2020-02-17 21:53 UTC, Roman-Khilevych commented
Де налаштовані основні елементи форм, хочаб що є на сторінці?

2020-02-17 21:54 UTC, Roman-Khilevych commented
Весь Less має бути в медіа міксинах.

2020-02-17 21:54 UTC, Roman-Khilevych commented
Форматування передивись.
Воно в тебе гуляє.

2020-02-17 21:57 UTC, Roman-Khilevych commented
Повидаляй копірайти дефолтні.

2020-02-17 22:29 UTC, worzewolf commented
> Де описані всі кольори змінними?

vendor->theme->web/css/source/_variables.less

2020-02-17 22:30 UTC, worzewolf commented
> Де налаштована типографія?

vendor->theme->web/css/source/_typography.less

2020-02-18 15:11 UTC, Roman-Khilevych commented
> > Де налаштована типографія?
> 
> vendor->theme->web/css/source/_typography.less

Ти тут лише попідключав шрифти.
Типографію ти не налаштував.

2020-02-18 15:16 UTC, Roman-Khilevych commented
> > Де описані всі кольори змінними?
> 
> vendor->theme->web/css/source/_variables.less

В тебе мають бути описані змінними шрифти.
Типу worzewolf-color-red
 Далі можеш робити background-color і тд і назначати змінну кольору.
Описані кольори мають бути в одону форматі ане один #fff другий lightgray третій rgba
Для напівпрозорості кольору в леса є міксин. І в той міксин засовуєш змінну з норм кольором.
В стилях всі кольори мають задаватися змінними, а не через раз.

2020-02-21 18:40 UTC, Roman-Khilevych requested changes

2020-02-21 18:40 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Magento_Cms/web/css/source/_homepage-gal.less
> +    font-weight: bold;
Typography

2020-02-21 18:40 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Magento_Cms/web/css/source/_homepage-gal.less
> +    position: absolute;
add class

2020-02-21 18:40 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Magento_Cms/web/css/source/_homepage-gal.less
> +    max-width: 1366px;
base variable

2020-03-02 14:38 UTC, Roman-Khilevych requested changes

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Catalog/templates/sidebar-banner.phtml
> +<img src="<?php echo $this->getViewFileUrl('images/Aside.png'); ?>" alt="some content">
Це цмс блок мав бути

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/layout/default.xml
> +                <block class="Magento\Framework\View\Element\Template" name="sidebar.banner" template="Magento_Catalog::sidebar-banner.phtml"/>
Цмс блок має бути.

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/web/css/source/_autostore-header.less
> +    background: black;
Чому тут блєк ане змінна?

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/web/css/source/_autostore-header.less
> +    color: white;
І тут

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/web/css/source/_autostore-header.less
> +        color: white;
І так далі

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/web/css/source/_autostore_footer.less
> +    //background: url("@{baseDir}images/Aside.png") no-repeat center center;
???

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/Magento_Theme/web/css/source/_autostore_footer.less
> +
Шо за дирки?

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/registration.php
> + *monnier default theme registration.
Який ж це моньєр?

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/autostore/default/web/css/source/lib/_responsive.less
> +//  */
Комент?

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/lib/_forms.less
> +// /**
Це ти нащо цей файл сюди перетягнув

2020-03-02 14:38 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/_theme.less
> +@monnier__link-color: @color-black;
ПОчитай комент до цього файла і зроби правильно)

2020-03-02 14:39 UTC, Roman-Khilevych commented
Де описані всі кольори?
Де налаштована типографія і основні елементи?

2020-03-19 14:45 UTC, Roman-Khilevych requested changes

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
> +            <button type="submit" >Submit</button>
Переклад?

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
> +            <!-- ko i18n:  'Additional charge' --><!-- /ko -->:&nbsp;
тут і без nbsp має працювати

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
> +</div>
Форматування поправ

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Catalog/templates/product/view/custom-tab.phtml
> +</div>
Це ти що виводиш в табу?
Захардкожений iframe?
Це атрибут мав виводитись. ПО типу таби дескріпшин

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Catalog/web/js/slider.js
> +        console.log(el.substring(0, el.length - 1));
?

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Catalog/web/js/slider.js
> +        $('#slider-range').slider({
Тут елемент приймай

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Theme/templates/html/topmenu.phtml
> +            <span class="all-categories-title">all categories</span>
Транслейт

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Theme/templates/html/topmenu.phtml
> +            <span>&nbsp;</span>
Зроби бургер якось гарніше.
Для прикладу <span class="burger-menu">Menu</span>

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Theme/web/css/source/_autostore-main.less
> +}
Пуста строка

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Theme/web/css/source/_autostore-main.less
> +}
Що це взагалі за файл?
Ці стилі треба було б перенести в правильні файли. В тебе тут все намішано.
Для категорії є свої файли, для продукта свої і тд... дивисьь по сорсмапах.

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/web/css/source/_theme.less
> +@button__border: 1px solid @autostore_color-alizarin;
А де типографія, інпути?

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/web/css/source/_typography.less
> + 0
?

2020-03-19 14:45 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/web/css/source/_typography.less
> +}
Ти дефолтні шрифти видалив? Верни. Або переопріділи дефолтні на свої

2020-03-21 19:01 UTC, worzewolf commented
@Roman-Khilevych, hope evything fixed.

2020-03-22 10:52 UTC, Roman-Khilevych requested changes

2020-03-22 10:52 UTC, Roman-Khilevych commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
>  </div>
Чому половина транслейтів пхп а остальні js?

2020-03-22 10:52 UTC, Roman-Khilevych commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
>  </div>
Небачу фікса

2020-03-22 10:52 UTC, Roman-Khilevych commented on app/design/frontend/avto/avtostore/Magento_Catalog/templates/product/view/custom-tab.phtml
> +<?php endif; ?>
+

2020-03-22 11:13 UTC, worzewolf commented on app/code/avto/Sample/view/frontend/templates/hw_table.phtml
>  </div>
справив на js

2020-03-22 11:19 UTC, merged