monnier less home work
Roman-Khilevych/OSS pull request #32
Opened 2020-02-20 02:15 UTC by NikOleks

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-02 14:11 UTC, Roman-Khilevych requested changes

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@color-gray127: #808080;
Звідки ти такі імена побрав для кольорів?
Онлайн є ресурси які підкажуть імя кольору по його коду.

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@color-gray127: #808080;
Свої кольори називай: @{назва теми}-color-{назва кольору}

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/lib/_responsive.less
> +//  */
Комент

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@font-size__67: 67px;
А що буде коли ти будеш змінювати розмір шрифта скрізь на сайті з 67 на 69?
Ти змінну будеш переіменовувати?
Використовуй абстрактні іменна.

2020-03-02 14:11 UTC, Roman-Khilevych commented on dev/tools/grunt/configs/local-themes.js
> +};
Пуста строка

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@screen__laptop: 1140px;
Хай буде вже. Але на майбутнє старайся обмежуватись мажентовськими брейкпоінтами.

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_theme.less
> +@form-element-input__width: 255px;
Типографію для H1 і тд було б добре додати.

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@text__color__base: @color-black;
Така змінна є схожа дефолтна. Чому її не використовуєш?

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/web/css/source/_footer.less
> +    .block_links .links_column:first-child .links_column__content > li:last-child {
Коротше це зробити не можна було? по класу наприклад?

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content__max-width: 1366px;
Де фолті змінні на це є.
@layout__max-width

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content-column__width: 50%;
Якщо це відноситься лише до сторінки едіторіал то вказуй це в змінній. Якщо загальні то перенеси в відповідний файл.

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content-title__font-size: @font-size__21;
І остальні передивись.

2020-03-02 14:11 UTC, Roman-Khilevych commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@card-title__font-size: 2 * @font-size__base;
Краще змінною окремою або вже просто числом тут задай.

2020-03-03 02:57 UTC, NikOleks commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@card-title__font-size: 2 * @font-size__base;
ok

2020-03-03 02:57 UTC, NikOleks commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content-title__font-size: @font-size__21;
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content-column__width: 50%;
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/Magento_Cms/web/css/source/_editorial.less
> +@main-content__max-width: 1366px;
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/_footer.less
> +    .block_links .links_column:first-child .links_column__content > li:last-child {
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@text__color__base: @color-black;
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/_theme.less
> +@form-element-input__width: 255px;
ok

2020-03-03 02:58 UTC, NikOleks commented on dev/tools/grunt/configs/local-themes.js
> +};
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@font-size__67: 67px;
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/lib/_responsive.less
> +//  */
ok

2020-03-03 02:58 UTC, NikOleks commented on app/design/frontend/testTheme/default/web/css/source/_variables.less
> +@color-gray127: #808080;
ok

2020-03-09 12:56 UTC, merged