monnier css to less
Roman-Khilevych/OSS pull request #33
Opened 2020-02-23 10:56 UTC by vlromaniuk

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/Magento_Theme/layout/default.xml
> +<!--        <css src="css/header_footer.css"/>-->
Це тут нашо?

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +    font-size: @monnier_h1_font_size;
Дефолтна змінна має бути.

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +    color: @monnier_base_text_color;
Дефолтна змінна має бути.

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        font-size: @monnier_defult_font_size;
Дефолтна змінна має бути.

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        color: @monnier_base_text_color;
Дефолтна змінна має бути.

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        color: @monnier_base_text_color;
Дефолтна змінна має бути.

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +  .blockImg{
Класи в одному стилі називай

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +      img{
Нашо тут така вложеність?

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +      max-width: 1315px;
Це з змінної має бути

2020-03-02 13:56 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/_extend.less
> +//  Magento extend fallback handling. Should be EMPTY.
нашо тут ці коменти?

2020-03-02 13:57 UTC, Roman-Khilevych commented
Де описані всі кольори змінними?
Де налаштована типографія?
Де налаштовані основні елементи?

2020-03-02 14:00 UTC, vlromaniuk commented
> Де описані всі кольори змінними?
> Де налаштована типографія?

в файлi _variable.less

2020-03-02 14:04 UTC, Roman-Khilevych commented
> > Де описані всі кольори змінними?
> > Де налаштована типографія?
> 
> в файлi _variable.less

На уроці мені повториш як я казав це все налаштовувати.
А зараз поправ все правильно.
Я не 1 раз говорив як це має бути.

2020-03-02 14:17 UTC, vlromaniuk commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        color: @monnier_base_text_color;
в якому планi дефолтну, типу дефолтну переопредiлити на свою чи як?

2020-03-02 14:21 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        color: @monnier_base_text_color;
@monnier_base_text_color - це твоя змінна. В маженті вже є подівні використовуй їх.
Передивися щераз в лібах всі міксини і які в них є змінні. І використовуй їх по максимуму.

2020-03-02 16:05 UTC, Roman-Khilevych commented
Пуш фікси зразу одним комітом, а не кусками. КОльори неправильно називаєш.

2020-03-02 16:13 UTC, vlromaniuk commented
> Пуш фікси зразу одним комітом, а не кусками. КОльори неправильно називаєш.

так я 1 комiтом i пофiксив

2020-03-02 16:15 UTC, Roman-Khilevych commented
> > Пуш фікси зразу одним комітом, а не кусками. КОльори неправильно називаєш.
> 
> так я 1 комiтом i пофiксив
ти хочеш сказати шо ти вже все пофіксив?

2020-03-20 11:06 UTC, Roman-Khilevych requested changes

2020-03-20 11:06 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +        font-size: @footer__font-size;
Це хіба футер?

2020-03-20 11:06 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/_theme.less
> +@form-element-input__font-size: @footer__font-size;
Чого футер?

2020-03-20 11:06 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/_theme.less
> +@navigation-desktop__font-weight: @footer__font-size;
Щось тут нетак

2020-03-20 11:06 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/source/_variables.less
> +@layout__max-width: 1364px;
Хіба немає дефолтної змінної для цього?

2020-03-20 11:06 UTC, Roman-Khilevych commented on app/design/frontend/monnier/default/web/css/_home_page.less
> +}
Форматування нормальне зроби

2020-03-20 13:29 UTC, merged