Auto Store
Roman-Khilevych/OSS pull request #35
Opened 2020-03-10 02:32 UTC by NikOleks

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-18 15:27 UTC, Roman-Khilevych requested changes

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/price-slider.phtml
> +</div>
+

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list.phtml
> +                        <span>sale</span>
Шотт треба зробити?)

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list.phtml
> +                        <span>new</span>
А тут?)

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/_extend.less
> +@import '_product.less';
+

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Checkout/layout/default.xml
> +<?xml version="1.0"?>
Тобі точно треба все що в цьому файлі?

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/layout/default.xml
> +    <update handle="default_head_blocks"/>
Це тут треба?

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/page_layout/2columns-left.xml
> +                <arguments>
Це працює в page layout?

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/page_layout/2columns-left.xml
> +</layout>
Це файл тобі взагалі не потрібний

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/sections.phtml
> +                                All Categories
???

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/i18n/en_US.csv
> +"Search entire store here...", "Search products..."
+

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/_globall.less
> +}
+

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/_mixins.less
> +}*/
На потім оставив?)

2020-03-18 15:27 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/_nav-section.less
> +}
Лишнє напевно

2020-03-21 17:49 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/price-slider.phtml
> +</div>
ok

2020-03-21 17:49 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list.phtml
> +                        <span>sale</span>
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list.phtml
> +                        <span>new</span>
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/_extend.less
> +@import '_product.less';
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Checkout/layout/default.xml
> +<?xml version="1.0"?>
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/sections.phtml
> +                                All Categories
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/i18n/en_US.csv
> +"Search entire store here...", "Search products..."
ok

2020-03-21 17:50 UTC, NikOleks commented on app/design/frontend/autoStore/default/web/css/source/_globall.less
> +}
ok

2020-03-21 17:51 UTC, NikOleks commented on app/design/frontend/autoStore/default/web/css/source/_mixins.less
> +}*/
ok

2020-03-21 17:51 UTC, NikOleks commented on app/design/frontend/autoStore/default/web/css/source/_nav-section.less
> +}
ok

2020-03-22 10:37 UTC, Roman-Khilevych requested changes

2020-03-22 10:37 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/web/js/products-slider.js
> +            $(element).owlCarousel({
В змінну це винеси, щоб кожен раз не шукати елемент.

2020-03-22 10:37 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/layout/default.xml
> +    </head>
Підключай на сторінках де карусель використовуєш

2020-03-22 10:37 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/copyright.phtml
> +            </ul>
CMS block

2020-03-22 10:38 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/page_layout/2columns-left.xml
> +</layout>
Чи потрібний?
В default.xml додавати цей блок пробував?

2020-03-22 10:39 UTC, Roman-Khilevych commented
Не побачив де ти табу кастомну додаєш.

2020-03-22 10:40 UTC, Roman-Khilevych commented
На майбутнє: більше працюй з дефолтними less файлами. Екстендь їх, оверрайдь якщо в них щось потрібно змінити. Менше такого як global, product і тд

2020-03-22 15:05 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Theme/web/js/products-slider.js
> +            $(element).owlCarousel({
ok

2020-03-22 15:05 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Theme/layout/default.xml
> +    </head>
ok

2020-03-22 15:05 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/copyright.phtml
> +            </ul>
ok

2020-03-22 15:06 UTC, NikOleks commented on app/design/frontend/autoStore/default/Magento_Theme/page_layout/2columns-left.xml
> +</layout>
ok

2020-03-22 15:31 UTC, merged