Romaniuk Autostore
Roman-Khilevych/OSS pull request #36
Opened 2020-03-13 11:09 UTC by vlromaniuk

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-19 17:48 UTC, Roman-Khilevych requested changes

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/code/autoStore/Sample/registration.php
> +autoStore module.
комент не правильний

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/code/autoStore/Sample/view/frontend/layout/cms_index_index.xml
> +<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
Нащо тут layout="2columns-left" ?

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
> +<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
layout="2columns-left"

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
> +</page>
Це все тобі тут треба?

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list/toolbar.phtml
> +
?

2020-03-19 17:48 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/js/carousel.js
> +        jQuery.noConflict();
ЦЕ шо тут таке?

2020-03-20 11:45 UTC, Roman-Khilevych requested changes

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
> +            <block class="Magento\Catalog\Block\Category\View" name="category.products" template="Magento_Catalog::category/products.phtml">
Це ти новий блок якийсь створюєш?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
> +                    <block class="Magento\Catalog\Block\Product\ProductList\Toolbar" name="product_list_toolbar" template="Magento_Catalog::product/list/toolbar.phtml">
А це?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list/items.phtml
> +                    <ol class="products list items product-items owl-carousel owl-theme" data-mage-init='{"carousel":{"baseUrl": "<?= $block->escapeJs($block->getBaseUrl());?>"}}'>
А для чого ти baseUrl сюди передаэш?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/templates/product/list/items.phtml
> +
Шо за дирка?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/_extend.less
> +//  Magento extend fallback handling. Should be EMPTY.
Я тобі про це ж вже писав

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/module/_toolbar.less
> +            @icon-arrow-up,
Форматування

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/module/_toolbar.less
> +}
Поправ форматування у всіх less файлах

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/js/carousel.js
> +        jQuery(".owl-carousel").owlCarousel({
$ передати нехоч?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/web/js/carousel.js
> +        jQuery(".owl-carousel").owlCarousel({
Подивись як правильно робляться js файли і перероби

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Checkout/templates/cart/minicart.phtml
> +
Забагато якось пустих строк

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Review/templates/helper/summary_short.phtml
> + *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
А це вже тут ну дуже цікаво.
Тобі лєнь було навіть копірайт поміняти в чужому темплейті?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/layout/default.xml
> +
Нащо стільки пустих строк?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/topmenu.phtml
> +    <li>contact us</li>
Це що тут взагалі таке?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/etc/view.xml
> +</view>
Не забагато тут всьго?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/etc/view.xml
> +</view>
Без його працювати не буде?

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/registration.php
> +autoStore theme.
??????

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/_extend.less
> +//  Magento extend fallback handling. Should be EMPTY.
????

2020-03-20 11:45 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/lib/_breadcrumbs.less
> +}
Ти ж казав що прибрав оверайди ліб

2020-03-20 11:46 UTC, Roman-Khilevych commented
Якщо в тебе едіторіал окремим МР-ом то навіщо ще тут файли дублюєш?

2020-03-20 11:47 UTC, vlromaniuk commented on app/design/frontend/autoStore/default/Magento_Catalog/web/css/source/_extend.less
> +//  Magento extend fallback handling. Should be EMPTY.
якраз зараз займаюсь цим

2020-03-20 12:46 UTC, vlromaniuk commented on app/design/frontend/autoStore/default/Magento_Theme/templates/html/topmenu.phtml
> +    <li>contact us</li>
а тут структуру в цмс блок було швидше писати, прошляпаив видалити

2020-03-20 18:24 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
>                  <block class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list" as="product_list" template="Magento_Catalog::product/list.phtml">
А тут? Ти новий блок створюєш? Для чого ти копіюєш стільки коду?

2020-03-20 18:24 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Review/templates/helper/summary_short.phtml
> + *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
Ти не відповів)

2020-03-20 18:28 UTC, Roman-Khilevych requested changes

2020-03-20 18:28 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/web/css/source/_theme.less
> +@h5__font-size: 10px;
Так краще)

2020-03-20 18:36 UTC, vlromaniuk commented on app/design/frontend/autoStore/default/Magento_Review/templates/helper/summary_short.phtml
> + *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
тоді коли був дедлайн до понеділка, я категорично не встигав і пвддався спокусі позичити один файл у вані

2020-03-20 18:36 UTC, vlromaniuk commented on app/design/frontend/autoStore/default/web/css/source/_theme.less
> +@h5__font-size: 10px;
я старався

2020-03-20 18:36 UTC, vlromaniuk commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
>                  <block class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list" as="product_list" template="Magento_Catalog::product/list.phtml">
якщо чесно я не памятаю, но без цього воно не працювало....

2020-03-21 11:58 UTC, Roman-Khilevych commented on app/design/frontend/autoStore/default/Magento_Catalog/layout/catalog_category_view.xml
>                  <block class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list" as="product_list" template="Magento_Catalog::product/list.phtml">
Ану попробуй через референси то зробити...

2020-03-21 12:18 UTC, Roman-Khilevych approved these changes

2020-03-21 15:12 UTC, merged